export const dbBookInsertExample = {
  _id: "id-00005",
  title: "Duna",
  author: ["Frank Herbert"],
  edition: "30ª edição",
  publication_year: 1965,
  publisher: "Chilton Books",
  publication_location: "Filadélfia",
  isbn: "9780441013593",
  volume: 1,
  genre: ["Ficção científica", "Clássicos"],
  inserted_by: "user_id-0001",
  created_at: new Date(2025, 0, 25),
  updated_at: new Date(2025, 0, 25),
};

export const dbBookExample2 = {
  _id: "id-00002",
  title: "O Hobbit",
  author: ["J. R. R. Tolkien"],
  edition: "Coleção Nova Fronteira",
  publication_year: 1937,
  publisher: "Nova Fronteira",
  publication_location: "Rio de Janeiro",
  isbn: "9788520904161",
  volume: 1,
  genre: ["Fantasia", "Clássicos"],
  inserted_by: "user_id-0001",
  created_at: new Date(2020, 5, 15),
  updated_at: new Date(2022, 3, 20),
};

export const dbBookExample3 = {
  _id: "id-00003",
  title: "As Crônicas de Nárnia",
  author: ["C. S. Lewis"],
  edition: "Coleção HarperCollins",
  publication_year: 1956,
  publisher: "HarperCollins",
  publication_location: "Londres",
  isbn: "9780066238500",
  volume: 1,
  genre: ["Fantasia", "Infantil"],
  inserted_by: "user_id-0001",
  created_at: new Date(2021, 1, 10),
  updated_at: new Date(2023, 0, 5),
};

export const dbBookExample4 = {
  _id: "id-00004",
  title: "A Saga da Fundação",
  author: ["Isaac Asimov"],
  edition: "Edição comemorativa",
  publication_year: 1951,
  publisher: "Doubleday",
  publication_location: "Nova York",
  isbn: "9780385121106",
  volume: 1,
  genre: ["Ficção científica", "Clássicos"],
  inserted_by: "user_id-0001",
  created_at: new Date(2019, 8, 22),
  updated_at: new Date(2023, 6, 30),
};

export const dbBookExample = {
  _id: "id-00001",
  title: "O Senhor dos Anéis",
  author: ["J. R. R. Tolkien"],
  edition: "Coleção Nova Fronteira",
  publication_year: 1954,
  publisher: "Nova Fronteira",
  publication_location: "Rio de Janeiro",
  isbn: "9788520908190",
  volume: 1,
  genre: ["Fantasia", "Clássicos"],
  inserted_by: "user_id-0001",
  created_at: new Date(2020, 2, 20),
  updated_at: new Date(2022, 2, 22),
};

export const inputBookUpdateExample = {
  id: "id-00001",
  title: "O Senhor dos Anéis",
  author: ["J. R. R. Tolkien"],
  edition: "Coleção Nova Fronteira",
  publication_year: 1954,
  publisher: "Nova Fronteira",
  publication_location: "Rio de Janeiro",
  isbn: "9788520908190",
  volume: 1,
  genre: ["Fantasia", "Clássicos"],
  inserted_by: "user_id-0001",
};
