enum BookGenre {
  // FICÇÃO
  ACTION_ADVENTURE = "AÇÃO E AVENTURA",
  CLASSICS = "CLÁSSICOS",
  COMEDY = "COMÉDIA",
  SHORT_STORIES = "CONTOS",
  DRAMA = "DRAMA",
  FANTASY = "FANTASIA",
  SCIENCE_FICTION = "FICÇÃO CIENTÍFICA",
  HISTORICAL_FICTION = "FICÇÃO HISTÓRICA",
  CRIME = "FICÇÃO POLICIAL/CRIME",
  HORROR = "HORROR/TERROR",
  MYSTERY = "MISTÉRIO/SUSPENSE",
  MAGICAL_REALISM = "REALISMO MÁGICO",
  ROMANCE = "ROMANCE",
  CONTEMPORARY_ROMANCE = "ROMANCE CONTEMPORÂNEO",
  HISTORICAL_ROMANCE = "ROMANCE HISTÓRIOCO",
  CHICK_LIT = "CHICK-LIT",
  PERIOD_ROMANCE = "ROMANCE DE ÉPOCA",
  THRILLER = "THRILLER/PSICOLÓGICO",
  TRAGEDY = "TRAGÉDIA",
  WESTERN = "WESTERN/FAROESTE",
  YOUNG_ADULT = "YOUNG ADULT (YA)",
  DYSTOPIAN = "DISTOPIA",

  // Não FICÇÃO
  AUTOBIOGRAPHY = "AUTOBIOGRAFIA",
  BIOGRAPHY = "BIOGRAFIA",
  MEMOIR = "MEMÓRIAS",
  HISTORY = "HISTÓRIA",
  SCIENCE = "CIÊNCIA E TECNOLOGIA",
  BUSINESS = "ECONOMIA E NEGÓCIOS",
  EDUCATION = "EDUCAÇÃO",
  PHILOSOPHY = "FILOSOFIA",
  PSYCHOLOGY = "PSICOLOGIA",
  RELIGION = "RELIGIÃO/ESPIRITUALIDADE",
  SELF_HELP = "AUTOAJUDA",
  HEALTH_WELLNESS = "SAÚDE E BEM-ESTAR",
  TRAVEL = "VIAGENS",
  ART_DESIGN = "ARTE E De DESIGN",
  COOKING = "GASTRONOMIA/CULINÁRIA",
  ESSAYS = "ENSAIOS",
  JOURNALISM = "JORNALISMO/REPORTAGEM",
  POLITICS = "POLÍTICA E SOCIEDADE",

  // Literatura Infantojuvenil
  FAIRY_TALES = "CONTOS DE FADAS",
  PICTURE_BOOKS = "LIVROS ILUSTRADOS",
  JUVENILE_FICTION = "FICÇÃO JUVENIL",
  FABLES = "FÁBULAS",

  // POESIA e Teatro
  LYRIC_POETRY = "POESIA LÍRICA",
  EPIC_POETRY = "POESIA ÉPICA",
  THEATER_TRAGEDY = "TRAGÉDIA TEATRAL",
  THEATER_COMEDY = "COMÉDIA TEATRAL",
  THEATER_DRAMA = "DRAMA TEATRAL",

  // Outros Gêneros
  ANTHOLOGY = "ANTOLOGIAS",
  MANGA_COMICS = "MANGAS E QUADRINHOS",
  INTERACTIVE_BOOKS = "LIVROS INTERATIVOS",
  REFERENCE = "GUIA DE REFERÊNCIA",
  EXPERIMENTAL_LITERATURE = "LITERATURA EXPERIMENTAL",
}

export default BookGenre;
